## пример  Persistent Volume (PV) и Persistent Volume Claim (PVC) для хранения файлов настроек
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
      - name: quiz-app
        image: your-quiz-app-image:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: config-storage
          mountPath: /app/settings.json
          subPath: settings.json
        - name: config-storage
          mountPath: /app/quiz_data.json
          subPath: quiz_data.json
        env:
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: quiz-secrets
              key: app-secret
      volumes:
      - name: config-storage
        persistentVolumeClaim:
          claimName: quiz-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quiz-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: quiz-secrets
type: Opaque
data:
  app-secret: base64-encoded-secret-value