apiVersion: v1
kind: ConfigMap
metadata:
  name: quiz-config
data:
  DATABASE_URL: "postgresql+psycopg2://quiz_user:$(DB_PASSWORD)@quiz-postgres:5432/quiz_db"
  APP_SECRET: "your-secret-key-change-in-production"
  SUPER_USERS: "k.skachilov"