apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  labels:
    app: quiz
spec:
  type: NodePort
  selector:
    app: quiz
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
