apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz
  labels:
    app: quiz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quiz
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: quiz
    spec:
      containers:
      - name: quiz
        image: yourregistry/quiz-rambler-app:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: quiz-config
        - secretRef:
            name: quiz-secret
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
