apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quiz-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - quiz.example.com
    secretName: quiz-tls
  rules:
  - host: quiz.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: quiz
            port:
              number: 80
